# Generated by Django 2.2.10 on 2021-01-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_pollanswer_pollquestionchoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollquestionchoice",
            old_name="question_choice",
            new_name="question",
        ),
    ]
